![Astrofisica Computacional](../../logo.PNG)

### Vectors and Arrays

In [13]:
A = [1 2 3]

1×3 Matrix{Int64}:
 1  2  3

In [17]:
B = [1; 2; 3]

3-element Vector{Int64}:
 1
 2
 3

In [15]:
A[1]

1

In [16]:
A[2]

2

In [18]:
B[2]

2

In [64]:
A[begin]

1

In [65]:
A[end]

3

In [66]:
C = [1 2 3 4 5 6 7 8 9 10]

1×10 Matrix{Int64}:
 1  2  3  4  5  6  7  8  9  10

In [75]:
size(C)

(1, 10)

In [77]:
size(C,1)

1

In [76]:
size(C,2)

10

In [67]:
C[begin:end]

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [68]:
C[begin:2:end]

5-element Vector{Int64}:
 1
 3
 5
 7
 9

In [69]:
C[2:3:8]

3-element Vector{Int64}:
 2
 5
 8

In [79]:
for i in 1:size(C,2)
    println("index :", i, "  element :", C[i])
end

index :1  element :1
index :2  element :2
index :3  element :3
index :4  element :4
index :5  element :5
index :6  element :6
index :7  element :7
index :8  element :8
index :9  element :9
index :10  element :10


In [19]:
M = [1 2 3; 4 5 6; 7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

Elements in the first row:

In [27]:
M[1,:]

3-element Vector{Int64}:
 1
 2
 3

Elements in the second column:

In [31]:
M[:,2]

3-element Vector{Int64}:
 2
 5
 8

Element in  the second row, third column

In [32]:
M[2,3]

6

We can improve the definition:

In [4]:
M = [1 2 3; 
     4 5 6; 
     7 8 9]

3×3 Matrix{Int64}:
 1  2  3
 4  5  6
 7  8  9

In [5]:
N = [1. 2 3; 
     4 5 6; 
     7 8 9]

3×3 Matrix{Float64}:
 1.0  2.0  3.0
 4.0  5.0  6.0
 7.0  8.0  9.0

In [6]:
T = ["Vainilla"; 
     10.; 
     5]

3-element Vector{Any}:
   "Vainilla"
 10.0
  5

### Array Comprehensions

When the vector has many components, it is possible to define its components in a more easy way:

In [8]:
V = [i for i = 1:50]

50-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10
 11
 12
 13
  ⋮
 39
 40
 41
 42
 43
 44
 45
 46
 47
 48
 49
 50

In [9]:
X = [1/n^2 for n = 1:30]

30-element Vector{Float64}:
 1.0
 0.25
 0.1111111111111111
 0.0625
 0.04
 0.027777777777777776
 0.02040816326530612
 0.015625
 0.012345679012345678
 0.01
 0.008264462809917356
 0.006944444444444444
 0.005917159763313609
 ⋮
 0.002770083102493075
 0.0025
 0.0022675736961451248
 0.002066115702479339
 0.001890359168241966
 0.001736111111111111
 0.0016
 0.0014792899408284023
 0.0013717421124828531
 0.0012755102040816326
 0.0011890606420927466
 0.0011111111111111111

In [10]:
sum(X)

1.6121501176015975

### Empty and Special Kind Arrays 

In [11]:
V = Float64[]

Float64[]

In [42]:
W = [] # The same as Any[]

Any[]

In [34]:
Z = zeros(2,4)

2×4 Matrix{Float64}:
 0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0

In [35]:
B = ones(3,2)

3×2 Matrix{Float64}:
 1.0  1.0
 1.0  1.0
 1.0  1.0

In [36]:
R = rand(4,2)

4×2 Matrix{Float64}:
 0.616635  0.897887
 0.788355  0.0359666
 0.899947  0.316522
 0.981472  0.541701

### Apply Scalar Functions to Arrays

In [57]:
X = [1; 2; 3]
Y = [2; 3; 5]

X+Y

3-element Vector{Int64}:
 3
 5
 8

In [48]:
X = [0 π/2 π]

1×3 Matrix{Float64}:
 0.0  1.5708  3.14159

In [49]:
sin(X)

LoadError: DimensionMismatch("matrix is not square: dimensions are (1, 3)")

In [50]:
sin(X[1])

0.0

In [51]:
sin.(X)

1×3 Matrix{Float64}:
 0.0  1.0  1.22465e-16

In [59]:
X = [2 3 5]

1×3 Matrix{Int64}:
 2  3  5

In [60]:
X^2

LoadError: DimensionMismatch("matrix A has dimensions (1,3), matrix B has dimensions (1,3)")

In [61]:
X.^2

1×3 Matrix{Int64}:
 4  9  25

In [62]:
Y = 2X.^2 + 3X.^4

1×3 Matrix{Int64}:
 56  261  1925

This can be written easily using the `broadcast` operator

In [63]:
Z = @. 2X^2 + 3X^4

1×3 Matrix{Int64}:
 56  261  1925

### Array Operations

Multiplication

In [83]:
A = rand(2,3)
B = rand(3,4)

A*B

2×4 Matrix{Float64}:
 0.291512  0.0944034  0.251347  0.425195
 1.2693    0.477207   1.202     1.7826

Element-wise multiplication

In [84]:
A = rand(2,3)
B = rand(2,3)
A .* B

2×3 Matrix{Float64}:
 0.121852  0.655838  0.469444
 0.259176  0.299928  0.174305

Dot product

In [85]:
V1 = rand(4)
V2 = rand(4)

dot(V1, V2)

0.9309107952639118

In [1]:
for i in 1:10
    println(i)
end

1
2
3
4
5
6
7
8
9
10


In [2]:
M = [i for i in 1:10]
M

10-element Vector{Int64}:
  1
  2
  3
  4
  5
  6
  7
  8
  9
 10

In [3]:
for i in 1:10, j in 1:5
    println(i,j)
end

11
12
13
14
15
21
22
23
24
25
31
32
33
34
35
41
42
43
44
45
51
52
53
54
55
61
62
63
64
65
71
72
73
74
75
81
82
83
84
85
91
92
93
94
95
101
102
103
104
105
