<img src="https://i.ibb.co/TcVMz44/logo.jpg" alt="logo" border="0" width=200>

# Computational Astrophysics 2021
---
## Eduard Larrañaga

Observatorio Astronómico Nacional\
Facultad de Ciencias\
Universidad Nacional de Colombia

---

## 01. Fundamentals of Python I


### About this notebook

In this notebook we present some of the fundamentals of `python` coding. Printing, simple functons, defining arrays and simple operations with arrays.

---


### Hello World!

In [ ]:
print('Hello World!')

Hello World!


---
### Importing Modules and Output Formatting

In [ ]:
import math

x = math.pi
print(f'An approximate value of pi is {x:.6f}')

An approximate value of pi is 3.141593


In [ ]:
print('An approximate value of pi is {:.5f}'.format(x))

An approximate value of pi is 3.14159


In [ ]:
print('An approximate value of pi is %5.5f'%x)

An approximate value of pi is 3.14159


Note the output formatting expression

`%[width][.precision]type`

`[width]` : Total number of digits (including decimal point)\
`[.precision]` : Digits in the decimal part of the number

`type` : <br>
d (Integer)\
f (float)\
e (Scientific Notation)\
g (same as 'e' if exponent is greater than -4 or less than precision, or equal as 'f' otherwise)

<br>
Complete information about output formatting can be found at

https://docs.python.org/3/tutorial/inputoutput.html


---
### Simple functions

In [ ]:
import math as m

x = m.pi / 2.0
m.sin(x)

1.0

In [ ]:
m.cos(x)

6.123233995736766e-17

In [ ]:
x = m.pi / 2
m.cos(x)

6.123233995736766e-17

In [ ]:
a = 2.0
b = 3.0
c = a + b
c

5.0

In [ ]:
a/b

0.6666666666666666

In [ ]:
m.sqrt(5*c)

5.0

In [ ]:
m.exp(10.)

22026.465794806718

In [ ]:
m.log(22026.47)

10.000000190915461

---
### Defining and manipulating arrays with `numpy` 

1-dimensional arrays

In [ ]:
import numpy as np

a = np.array([0., 2., 4., 6. ])
a

array([0., 2., 4., 6.])

In [ ]:
b = np.arange(10)
b

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
c = np.zeros(10,float)
c

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [ ]:
d = np.ones(10)
d

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [ ]:
e = np.linspace(1., 20., 10)
e

array([ 1.        ,  3.11111111,  5.22222222,  7.33333333,  9.44444444,
       11.55555556, 13.66666667, 15.77777778, 17.88888889, 20.        ])

In [ ]:
f = np.random.random(10)
f

array([0.38124073, 0.98668114, 0.18252274, 0.80706627, 0.10817881,
       0.55554631, 0.51934693, 0.22713895, 0.28599086, 0.4068659 ])

n-dimensional arrays

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
a[0]

array([1, 2, 3])

In [ ]:
a[1]

array([4, 5, 6])

In [ ]:
a[1,2]

6

In [ ]:
a[1,:]

array([4, 5, 6])

In [ ]:
a[:,1]

array([2, 5, 8])

In [ ]:
a[:]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.array([np.arange(3),np.zeros(3),np.arange(3)])

array([[0., 1., 2.],
       [0., 0., 0.],
       [0., 1., 2.]])

In [ ]:
np.zeros([3,3],float)

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
np.ones([4,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
np.random.random([3,4])

array([[0.27211098, 0.51693874, 0.51877928, 0.51368794],
       [0.51344094, 0.367365  , 0.14527115, 0.34051978],
       [0.47583003, 0.21084499, 0.99192627, 0.73955583]])

Attributes of an array

In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
np.ndim(a)

2

In [ ]:
a.shape

(3, 3)

In [ ]:
a.max()

9

In [ ]:
a.min()

1

In [ ]:
a.sum()

45

In [ ]:
a[0,:].sum()

6

In [ ]:
a[:,1].sum()

15

In [ ]:
a.mean()

5.0

---
### Simple Operations with Arrays

In [ ]:
import numpy as np

a = np.random.random([3,3])
b = np.random.random([3,3])
a, b

(array([[0.60696464, 0.10686803, 0.10103011],
        [0.22225435, 0.84556846, 0.16211763],
        [0.80426753, 0.50096951, 0.45891304]]),
 array([[0.34327724, 0.2938002 , 0.37366434],
        [0.10429228, 0.49074258, 0.83086732],
        [0.16512976, 0.10424922, 0.781681  ]]))

In [ ]:
c = a + 2
c

array([[2.60696464, 2.10686803, 2.10103011],
       [2.22225435, 2.84556846, 2.16211763],
       [2.80426753, 2.50096951, 2.45891304]])

In [ ]:
d = a + b
d

array([[0.95024188, 0.40066823, 0.47469445],
       [0.32654663, 1.33631103, 0.99298495],
       [0.96939729, 0.60521872, 1.24059404]])

In [ ]:
a*2

array([[1.21392928, 0.21373606, 0.20206021],
       [0.44450871, 1.69113691, 0.32423526],
       [1.60853506, 1.00193901, 0.91782608]])

In [ ]:
e = a * b   # Elementwise product
e

array([[0.20835715, 0.03139785, 0.03775135],
       [0.02317941, 0.41495644, 0.13469824],
       [0.1328085 , 0.05222568, 0.3587236 ]])

In [ ]:
f = a @ b   # matrix product
f

array([[0.23618574, 0.24130333, 0.39456751],
       [0.19125157, 0.49715545, 0.91232799],
       [0.40411419, 0.52998235, 1.07548889]])

In [ ]:
f = a.dot(b) # matrix product (alternative)
f

array([[0.23618574, 0.24130333, 0.39456751],
       [0.19125157, 0.49715545, 0.91232799],
       [0.40411419, 0.52998235, 1.07548889]])

In [ ]:
g = a / b # Elementwise 
g

array([[1.76814704, 0.3637439 , 0.27037663],
       [2.13107207, 1.72303871, 0.19511856],
       [4.87051841, 4.80549906, 0.58708481]])

In [ ]:
10*np.sin(c)

array([[5.09520995, 8.59721737, 8.62688864],
       [7.95200574, 2.91719652, 8.30204831],
       [3.30964149, 5.97695149, 6.30874359]])

In [ ]:
np.exp(d)

array([[2.58633518, 1.49282191, 1.60752294],
       [1.38617289, 3.80498114, 2.69927967],
       [2.63635502, 1.83165279, 3.45766684]])

In [ ]:
np.log10(f)

array([[-0.62674634, -0.61743668, -0.40387868],
       [-0.718395  , -0.30350779, -0.039849  ],
       [-0.3934959 , -0.27573859,  0.03160593]])

Changing the shape of an array

In [ ]:
a = np.random.random([3,4])
a.shape

(3, 4)

In [ ]:
a

array([[0.80626838, 0.38596399, 0.10926556, 0.12191527],
       [0.11454283, 0.16397455, 0.62201442, 0.13773725],
       [0.14132333, 0.19183533, 0.22103615, 0.6732673 ]])

In [ ]:
a.T # Transpose 

array([[0.80626838, 0.11454283, 0.14132333],
       [0.38596399, 0.16397455, 0.19183533],
       [0.10926556, 0.62201442, 0.22103615],
       [0.12191527, 0.13773725, 0.6732673 ]])

In [ ]:
a.T.shape

(4, 3)

In [ ]:
a.ravel() #flattens the array

array([0.80626838, 0.38596399, 0.10926556, 0.12191527, 0.11454283,
       0.16397455, 0.62201442, 0.13773725, 0.14132333, 0.19183533,
       0.22103615, 0.6732673 ])

In [ ]:
a.reshape(6,2)

array([[0.80626838, 0.38596399],
       [0.10926556, 0.12191527],
       [0.11454283, 0.16397455],
       [0.62201442, 0.13773725],
       [0.14132333, 0.19183533],
       [0.22103615, 0.6732673 ]])

In [ ]:
a

array([[0.80626838, 0.38596399, 0.10926556, 0.12191527],
       [0.11454283, 0.16397455, 0.62201442, 0.13773725],
       [0.14132333, 0.19183533, 0.22103615, 0.6732673 ]])