![Astrofisica Computacional](../../../logo.png)

---
# 01. Introduction to `NumPy`

Eduard Larrañaga (ealarranaga@unal.edu.co)

---

### About this notebook

In this notebook we present an introduction to the `numpy` package. 

---

In [1]:
import numpy as np
import sys

print(f"Python version:  {sys.version}\n"
      f"NumPy version:   {np.__version__}")


Python version:  3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:24:55) 
[Clang 11.1.0 ]
NumPy version:   1.19.5


## Arrays in NumPy: `ndarray`

A 1-dimensional array

In [2]:
a = np.array([1., 2., 3., 4., 5.])
a

array([1., 2., 3., 4., 5.])

In [3]:
type(a)

numpy.ndarray

## Properties of an array

In [4]:
a.size  # Gives the number of elements in the array

5

In [5]:
a.ndim  # Number of dimensions of the array

1

In [6]:
a.shape  # Shape of the array

(5,)

In [7]:
a.dtype  # Type of the elements in the array

dtype('float64')

Multi-dimensional Arrays

In [8]:
b = np.array([[1., 2., 3.],[4., 5., 6.], [7., 8., 9.]])
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [9]:
print(type(b))
print(b.size)
print(b.ndim)
print(b.shape)
print(b.dtype)

<class 'numpy.ndarray'>
9
2
(3, 3)
float64


## Array Methods

In [10]:
a

array([1., 2., 3., 4., 5.])

Minimum, maximum and mean

In [11]:
a.min(), a.max(), a.mean()

(1.0, 5.0, 3.0)

Sum of elements

In [12]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [13]:
b.sum()

45.0

In [14]:
b.sum(axis=0)

array([12., 15., 18.])

In [15]:
b.sum(axis=1)

array([ 6., 15., 24.])

In [16]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [17]:
b.T # Transpose of b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [18]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
b = b.T

In [20]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

## Operations with Arrays

In [21]:
a

array([1., 2., 3., 4., 5.])

In [22]:
a + 5.

array([ 6.,  7.,  8.,  9., 10.])

In [23]:
a*np.pi/2.

array([1.57079633, 3.14159265, 4.71238898, 6.28318531, 7.85398163])

$a^e$

In [24]:
a**np.e

array([ 1.        ,  6.58088599, 19.81299075, 43.30806043, 79.43235917])

$e^a$

In [25]:
np.e**a

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

Products of arrays

In [26]:
a

array([1., 2., 3., 4., 5.])

In [27]:
a * a  # Element-wise product

array([ 1.,  4.,  9., 16., 25.])

In [28]:
a @ a  # Matrix Product

55.0

In [29]:
np.dot(a,a) # Equivalent form of the matrix product

55.0

Other operations

In [30]:
a

array([1., 2., 3., 4., 5.])

In [31]:
a < 3

array([ True,  True, False, False, False])

In [32]:
a == 4

array([False, False, False,  True, False])

Other operations

In [33]:
(a > 3) & (a < 5)  # bitwise AND

array([False, False, False,  True, False])

In [34]:
a < np.array([2, 3, 5, 2, 1])

array([ True,  True,  True, False, False])

In [35]:
a

array([1., 2., 3., 4., 5.])

In [36]:
a < 3

array([ True,  True, False, False, False])

In [37]:
np.sum(a < 3) 

2

## Indices and Slicing

In [38]:
a

array([1., 2., 3., 4., 5.])

In [43]:
a[0]  # Remember that indices start at 0

1.0

In [47]:
a[-1]  # Index [-1] refers to the last element

5.0

In [49]:
a[2:6] # Indices [start:end]

array([3., 4., 5.])

In [50]:
a[2:6:2]  # Indices [start:end:step]

array([3., 5.])

In [51]:
a[::-1]  # Reverse an array

array([5., 4., 3., 2., 1.])

### Indixing and Slicing in Multiple Dimensions

In [52]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [55]:
b[0]

array([1., 4., 7.])

In [58]:
b[2, 2]

9.0

In [59]:
b[:,1] # The symbol `:` selects the whole axis

array([4., 5., 6.])

In [62]:
b[0, 1:4]

array([4., 7.])

In [63]:
b[:, 1:3]  

array([[4., 7.],
       [5., 8.],
       [6., 9.]])

In [64]:
b[:, 0:5:2]

array([[1., 7.],
       [2., 8.],
       [3., 9.]])

In [65]:
b[::-1]  # reverses axis 0

array([[3., 6., 9.],
       [2., 5., 8.],
       [1., 4., 7.]])

In [66]:
b[::-1, ::-1]  # reverses both axes

array([[9., 6., 3.],
       [8., 5., 2.],
       [7., 4., 1.]])

## Advanced Indexing

In [67]:
d = np.array([10, 15, 2., 5, 10, 2, 1])
d

array([10., 15.,  2.,  5., 10.,  2.,  1.])

In [68]:
mask = np.array([True, False, False, True, False, True, True])
mask

array([ True, False, False,  True, False,  True,  True])

In [69]:
d[mask]

array([10.,  5.,  2.,  1.])

In [70]:
d[[0,3,5,6]]

array([10.,  5.,  2.,  1.])

In [71]:
d[[1, 3, 1, 6]]

array([15.,  5., 15.,  1.])

## Helper Functions to Create Arrays

In [72]:
np.arange(7) # Creates array from a range of integers

array([0, 1, 2, 3, 4, 5, 6])

In [73]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [74]:
np.arange(2,7,2)

array([2, 4, 6])

In [75]:
np.linspace(1, 5, 10) #[start, end, number of points in the interval]

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [76]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [77]:
np.ones(10, dtype='i') # Creates an array with ones of the integer type

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [78]:
np.ones(10, dtype='i2')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [79]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [80]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [83]:
np.zeros(5, dtype='i')

array([0, 0, 0, 0, 0], dtype=int32)

In [84]:
np.zeros([2, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [85]:
np.empty(20) # Empty array 

array([0.00000000e+000, 5.63234836e-322, 0.00000000e+000, 0.00000000e+000,
       2.41907520e-312, 1.15998412e-028, 2.44171989e+232, 8.00801729e+159,
       6.19319847e-071, 1.03080219e+136, 6.01347002e-154, 7.19733212e+140,
       6.01347002e-154, 1.55736280e-033, 4.56295599e-144, 2.86530729e+161,
       8.93176633e+271, 4.98131536e+151, 1.78820115e-047, 1.58357921e-319])

In [86]:
np.eye(4) # n-dimensional identity array 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [87]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [88]:
np.ones_like(b) # Array with the shape of array b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Random numbers

In [96]:
np.random.random((3,4))

array([[0.8382467 , 0.42607299, 0.36110186, 0.29141662],
       [0.32674025, 0.03946558, 0.52917507, 0.52819128],
       [0.60702358, 0.35369141, 0.73771727, 0.13828524]])

In [100]:
rng = np.random.default_rng(413)  # Starts the random number generator with seed=413

In [101]:
rng.random((3, 4)) # random number array between 0 and 1  with (shape)

array([[0.04622048, 0.48625808, 0.03210341, 0.07850197],
       [0.99893742, 0.79251717, 0.14096539, 0.20539366],
       [0.39306974, 0.14090258, 0.99557315, 0.68259742]])

In [102]:
rng.integers(1, 10, (3, 10)) # (min, max, shape)

array([[4, 4, 5, 9, 6, 3, 6, 7, 4, 2],
       [7, 5, 9, 1, 4, 1, 3, 4, 2, 4],
       [9, 6, 2, 2, 6, 8, 1, 4, 3, 9]])

In [103]:
rng.uniform(0, 5, (2,5)) # Samples are uniformly distributed over the interval (min, max, shape)

array([[4.6239944 , 3.26359437, 2.9543661 , 2.97639479, 3.62314861],
       [4.6588422 , 3.35944474, 0.31380207, 0.32887797, 2.54815115]])

## Changing the shape of an array

In [104]:
c = np.arange(16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [107]:
c.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [108]:
g = np.array([0,1,2,3])
g

array([0, 1, 2, 3])

In [109]:
g.shape

(4,)

In [110]:
newg = g[:, np.newaxis]  # inserts a new axis, making it two dimensional
newg

array([[0],
       [1],
       [2],
       [3]])

In [111]:
newg.shape

(4, 1)

Flatten an array

In [112]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

In [113]:
b.ravel()

array([1., 4., 7., 2., 5., 8., 3., 6., 9.])

In [114]:
b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

## Universal Functions (`ufunc`)

A `ufunc` is a **vectorized wrapper** for a function that takes as inputs the components of an array and returns an equalnumber of outputs.
- Math operations (`add()`, `subtract()`, `square()`, `log10()`, ...)
- Trigonometric functions (`sin()`, `cos()`, `tan()`, `deg2rad()`, ...)
- Comparison functions (`greater()`, `less_equal()`, `fmax()`, ...)

The universal functions all are subclasses of `np.ufunc`

In [ ]:
type(np.cos)  # they all are subclasses of np.ufunc

In [ ]:
b

In [ ]:
np.sqrt(b)

In [ ]:
np.cos(b)

## Creating your own `ufunc` 
It is possible to create a new `ufunc` using `np.frompyfunc(func, nin, nout)`

In [ ]:
x = rng.integers(0, 100, 10)
x

In [ ]:
def f(x):
    return 1 if x > 23 else 0

In [ ]:
f(x) # This will raise an error of interpretation

In [ ]:
uf = np.frompyfunc(f, 1, 1)

In [ ]:
uf(x)

In [ ]:
uf(50)

## Copies of an array

In [115]:
original = np.arange(10)
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [116]:
ref_to_original = original # The new object will point to `original`
ref_to_original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [117]:
ref_to_original[2]= 100
ref_to_original

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [118]:
original

array([  0,   1, 100,   3,   4,   5,   6,   7,   8,   9])

In [119]:
ref_to_original[2] = 99

original   # changing `ref_to_original` has changed `original` !!!!

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

In [120]:
original = np.arange(10)

copy_of_original = np.copy(original) # Create a copy of the array
copy_of_original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [121]:
copy_of_original[2] = 99

copy_of_original, original   # changing `copy_of_original` doesn't change `original` !!!!

(array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [122]:
original = np.arange(10)

single_value = original[5]  # single element access returns a copy
single_value

5

In [123]:
single_value = 9999
original             # not affected when `single_value` is changed

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Slices

In [ ]:
original = np.arange(10)

a_slice = original[2:4]    # slice of original
a_slice

In [ ]:
a_slice[1] = 1000  # changing elements of `a_slice` changes to `original`
a_slice, original

In [ ]:
original[3:6] = [101, 102, 103]   # changing 'original' also changes 'slice'
a_slice

## Speed Comparisons

In [124]:
def my_mean(numbers):
    s = 0
    N = len(numbers)
    for i in range(N):
        s += numbers[i]
    return s/N

numbers = np.arange(1000000)
%timeit my_mean(numbers)

118 ms ± 2.4 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [125]:
def my_mean(numbers):
    return sum(numbers)/len(numbers)

numbers = list(range(1000000))
%timeit my_mean(numbers) # Defined function

5.16 ms ± 40.4 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [126]:
numbers = np.arange(1000000)
%timeit np.mean(numbers) # Numpy function

309 µs ± 3.34 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [ ]:
conda install numba

In [127]:
import numba as nb

@nb.jit
def my_mean(numbers):
    s = 0
    N = len(numbers)
    for i in range(N):
        s += numbers[i]
    return s/N

numbers = np.arange(1000000)
%timeit my_mean(numbers)

189 µs ± 2.11 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Speed Comparisons

In [128]:
def my_sum(N):
    s = 0
    for i in range(N):
        s +=i
    return s

%timeit my_sum(100000000)

2.87 s ± 50.6 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [129]:
numbers_to_sum = np.arange(100000000)
%timeit np.sum(numbers_to_sum)

38.1 ms ± 250 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [130]:
@nb.jit
def my_sum(N):
    s = 0
    for i in range(N):
        s +=i
    return s

%timeit my_sum(100000000)

88.5 ns ± 0.36 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


Use of built-in function is encouraged !!!