![Astrofisica Computacional](../../../logo.png)

---
## 03. Reading and Writting Files
Eduard Larrañaga (ealarranaga@unal.edu.co)

---

### About this notebook

In this notebook we present some of the fundamentals of `python` coding.  Reading and Writing files

---

### Reading Files

Using `numpy`, it is possible to store the data in a numpy array directly from the file. 

The file 'exampe_file1.txt' has values separated by a space.

In [1]:
import numpy as np

data = np.loadtxt('example_file1.txt', comments='#')
data

array([[0.        , 0.        ],
       [0.01886842, 0.01886709],
       [0.03773685, 0.03772621],
       [0.05660527, 0.05656938],
       [0.0754737 , 0.07538864],
       [0.09434212, 0.09417604],
       [0.11321055, 0.11292363],
       [0.13207897, 0.1316235 ]])

In [2]:
data[:,0]

array([0.        , 0.01886842, 0.03773685, 0.05660527, 0.0754737 ,
       0.09434212, 0.11321055, 0.13207897])

In [3]:
data[:,1]

array([0.        , 0.01886709, 0.03772621, 0.05656938, 0.07538864,
       0.09417604, 0.11292363, 0.1316235 ])

In [5]:
#data2 = np.loadtxt('example_file2.txt', comments='#')



The file 'exampe_file2.txt' has values separated by a comma. Hence we use the delimiter argument,

In [6]:
data2 = np.loadtxt('example_file2.txt', comments='#', delimiter=',')
data2

array([[0.        , 0.        ],
       [0.01886842, 0.01886709],
       [0.03773685, 0.03772621],
       [0.05660527, 0.05656938],
       [0.0754737 , 0.07538864],
       [0.09434212, 0.09417604],
       [0.11321055, 0.11292363],
       [0.13207897, 0.1316235 ]])

In [7]:
data2[:,0]

array([0.        , 0.01886842, 0.03773685, 0.05660527, 0.0754737 ,
       0.09434212, 0.11321055, 0.13207897])

---
### Writting a File

Writting a file with 50 samples of random data

In [8]:
import numpy as np

data = np.random.random([50,2])

np.savetxt('out_file1.txt', data, fmt='%5.5f', header='This is the header of the file')

Writting with comma delimiters

In [9]:
import numpy as np

data = np.random.random([50,2])

np.savetxt('out_file2.txt', data, delimiter = ',', 
           fmt='%5.5f', header='This is the header of the file')

In [13]:
data = np.random.random([10,2])
data

array([[0.51519156, 0.85072711],
       [0.36341212, 0.12980355],
       [0.85502223, 0.18859031],
       [0.23380711, 0.37681762],
       [0.76528201, 0.42661023],
       [0.21944297, 0.94164689],
       [0.03847201, 0.65209512],
       [0.07847495, 0.48551266],
       [0.20545049, 0.32050774],
       [0.8839898 , 0.0682924 ]])

In [14]:
np.savetxt('out_file3.data', data, delimiter = ',', 
           fmt='%5.5f', header='This is the header of the file')