![Astrofisica Computacional](../logo.png)

---
# 01. Introduction to `NumPy`

Eduard Larrañaga (ealarranaga@unal.edu.co)

---

### About this notebook

In this notebook we present an introduction to the `numpy` package. 

---

In [2]:
import numpy as np
import sys

print(f"Python version:  {sys.version}\n"
      f"NumPy version:   {np.__version__}")


Python version:  3.9.5 | packaged by conda-forge | (default, Jun 19 2021, 00:24:55) 
[Clang 11.1.0 ]
NumPy version:   1.20.3


## Arrays in NumPy: `ndarray`

A 1-dimensional array

In [10]:
a = np.array([1., 2., 3., 4., 5.])
a

array([1., 2., 3., 4., 5.])

In [11]:
type(a)

numpy.ndarray

## Properties of an array

In [12]:
a.size  # Gives the number of elements in the array

5

In [13]:
a.ndim  # Number of dimensions of the array

1

In [14]:
a.shape  # Shape of the array

(5,)

In [15]:
a.dtype  # Type of the elements in the array

dtype('float64')

Multi-dimensional Arrays

In [3]:
b = np.array([[1., 2., 3.],[4., 5., 6.], [7., 8., 9.]])
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [19]:
print(type(b))
print(b.size)
print(b.ndim)
print(b.shape)
print(b.dtype)

<class 'numpy.ndarray'>
9
2
(3, 3)
float64


## Array Methods

In [22]:
a

array([1., 2., 3., 4., 5.])

Minimum, maximum and mean

In [23]:
a.min(), a.max(), a.mean()

(1.0, 5.0, 3.0)

Sum of elements

In [24]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [25]:
b.sum()

45.0

In [26]:
b.sum(axis=0)

array([12., 15., 18.])

In [27]:
b.sum(axis=1)

array([ 6., 15., 24.])

In [143]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [144]:
b.T # Transpose of b

array([[1., 4., 7.],
       [2., 5., 8.],
       [3., 6., 9.]])

## Operations with Arrays

In [28]:
a

array([1., 2., 3., 4., 5.])

In [29]:
a - 5.

array([-4., -3., -2., -1.,  0.])

In [31]:
a*np.pi/2.

array([1.57079633, 3.14159265, 4.71238898, 6.28318531, 7.85398163])

$a^e$

In [32]:
a**np.e

array([ 1.        ,  6.58088599, 19.81299075, 43.30806043, 79.43235917])

$e^a$

In [33]:
np.e**a

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

Products of arrays

In [34]:
a * a  # Element-wise product

array([ 1.,  4.,  9., 16., 25.])

In [35]:
a @ a  # Matrix Product

55.0

In [36]:
np.dot(a,a) # Equivalent form of the matrix product

55.0

Other operations

In [37]:
a

array([1., 2., 3., 4., 5.])

In [38]:
a < 3

array([ True,  True, False, False, False])

In [39]:
a == 4

array([False, False, False,  True, False])

Other operations

In [40]:
(a > 3) & (a < 5)  # bitwise AND

array([False, False, False,  True, False])

In [43]:
a < np.array([2, 3, 5, 2, 1])

array([ True,  True,  True, False, False])

In [44]:
np.sum(a > 2)

3

## Indices and Slicing

In [45]:
a[0]  # Remember that indices start at 0

1.0

In [46]:
a[-1]  # Index [-1] refers to the last element

5.0

In [48]:
a[2:5] # Indices [start:end]

array([3., 4., 5.])

In [50]:
a[2:6:2]  # Indices [start:end:step]

array([3., 5.])

In [51]:
a[::-1]  # Reverse an array

array([5., 4., 3., 2., 1.])

### Indixing and Slicing in Multiple Dimensions

In [53]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [56]:
b[1]

array([4., 5., 6.])

In [57]:
b[0, 2]

3.0

In [63]:
b[:,1] # The symbol `:` selects the whole axis

array([2., 5., 8.])

In [58]:
b[0, 1:4]

array([2., 3.])

In [59]:
b[:, 1:4]  

array([[2., 3.],
       [5., 6.],
       [8., 9.]])

In [62]:
b[:, 0:5:2]

array([[1., 3.],
       [4., 6.],
       [7., 9.]])

In [33]:
b[::-1]  # reverses axis 0

array([[ 6,  7,  8,  9, 10],
       [ 1,  2,  3,  4,  5]])

In [39]:
b[::-1, ::-1]  # reverses both axes

array([[10,  9,  8,  7,  6],
       [ 5,  4,  3,  2,  1]])

## Advanced Indexing

In [65]:
d = np.array([10, 15, 2., 5, 10, 2, 1])
d

array([10., 15.,  2.,  5., 10.,  2.,  1.])

In [66]:
mask = np.array([True, False, False, True, False, True, True])
mask

array([ True, False, False,  True, False,  True,  True])

In [67]:
d[mask]

array([10.,  5.,  2.,  1.])

In [69]:
d[[1, 3, 1, 6]]

array([15.,  5., 15.,  1.])

## Helper Functions to Create Arrays

In [70]:
np.arange(7) # Creates array from a range of integers

array([0, 1, 2, 3, 4, 5, 6])

In [71]:
np.arange(2,7)

array([2, 3, 4, 5, 6])

In [72]:
np.arange(2,7,2)

array([2, 4, 6])

In [85]:
np.linspace(1, 5, 10) #[start, end, number of points in the interval]

array([1.        , 1.44444444, 1.88888889, 2.33333333, 2.77777778,
       3.22222222, 3.66666667, 4.11111111, 4.55555556, 5.        ])

In [72]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [73]:
np.ones(10, dtype='i') # Creates an array with ones of the integer type

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int32)

In [79]:
np.ones(10, dtype='i2')

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1], dtype=int16)

In [74]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [75]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [78]:
np.zeros(5, dtype='i')

array([0, 0, 0, 0, 0], dtype=int32)

In [77]:
np.zeros([2, 4])

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [80]:
np.empty(20) # Empty array 

array([1.49166815e-154, 1.49166815e-154, 6.42285340e-323, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 1.11275125e-308,
       0.00000000e+000, 0.00000000e+000, 0.00000000e+000, 0.00000000e+000])

In [84]:
np.eye(4) # n-dimensional identity array 

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [86]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [87]:
np.ones_like(b) # Array with the shape of array b

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

## Random numbers

In [ ]:
rng = np.random.default_rng(413)  # Starts the random number generator with seed=413

In [82]:
rng.random((3, 4)) # random number array between 0 and 1  with (shape)

array([[0.75808774, 0.35452597, 0.97069802, 0.89312112],
       [0.7783835 , 0.19463871, 0.466721  , 0.04380377],
       [0.15428949, 0.68304895, 0.74476216, 0.96750973]])

In [90]:
rng.integers(1, 10, (3, 10)) # (min, max, shape)

array([[1, 6, 6, 7, 7, 9, 1, 7, 4, 1],
       [7, 1, 9, 5, 5, 9, 8, 3, 3, 9],
       [7, 5, 6, 2, 7, 8, 1, 1, 2, 9]])

In [93]:
rng.uniform(0, 5, (2,5)) # Samples are uniformly distributed over the interval (min, max, shape)

array([[2.91826287, 1.41765594, 1.22710122, 3.50541522, 1.40658072],
       [2.94922296, 2.09703076, 4.48273826, 0.06769523, 1.3976997 ]])

## Changing the shape of an array

In [97]:
c = np.arange(16)
c

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [98]:
c.reshape(4, 4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [111]:
g = np.array([0,1,2,3])
g

array([0, 1, 2, 3])

In [112]:
g.shape

(4,)

In [113]:
newg = g[:, np.newaxis]  # inserts a new axis, making it two dimensional
newg

array([[0],
       [1],
       [2],
       [3]])

In [114]:
newg.shape

(4, 1)

Flatten an array

In [4]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [5]:
b.ravel()

array([1., 2., 3., 4., 5., 6., 7., 8., 9.])

## Universal Functions (`ufunc`)

A `ufunc` is a **vectorized wrapper** for a function that takes as inputs the components of an array and returns an equalnumber of outputs.
- Math operations (`add()`, `subtract()`, `square()`, `log10()`, ...)
- Trigonometric functions (`sin()`, `cos()`, `tan()`, `deg2rad()`, ...)
- Comparison functions (`greater()`, `less_equal()`, `fmax()`, ...)

The universal functions all are subclasses of `np.ufunc`

In [94]:
type(np.cos)  # they all are subclasses of np.ufunc

numpy.ufunc

In [115]:
b

array([[1., 2., 3.],
       [4., 5., 6.],
       [7., 8., 9.]])

In [116]:
np.sqrt(b)

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974],
       [2.64575131, 2.82842712, 3.        ]])

In [118]:
np.cos(b)

array([[ 0.54030231, -0.41614684, -0.9899925 ],
       [-0.65364362,  0.28366219,  0.96017029],
       [ 0.75390225, -0.14550003, -0.91113026]])

## Creating your own `ufunc` 
It is possible to create a new `ufunc` using `np.frompyfunc(func, nin, nout)`

In [120]:
x = rng.integers(0, 100, 10)
x

array([25, 61,  7, 74, 74, 28, 70, 49, 49, 72])

In [121]:
def f(x):
    return 1 if x > 23 else 0

In [123]:
f(x) # This will raise an error of interpretation

ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [124]:
uf = np.frompyfunc(f, 1, 1)

In [125]:
uf(x)

array([1, 1, 0, 1, 1, 1, 1, 1, 1, 1], dtype=object)

In [126]:
f(5)

0

## Copies of an array

In [127]:
original = np.arange(10)
original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [128]:
ref_to_original = original # The new object will point to `original`
ref_to_original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [129]:
ref_to_original[2] = 99

original   # changing `ref_to_original` has changed `original` !!!!

array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9])

In [134]:
original = np.arange(10)

copy_of_original = np.copy(original) # Create a copy of the array
copy_of_original

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [135]:
copy_of_original[2] = 99

copy_of_original, original   # changing `copy_of_original` doesn't change `original` !!!!

(array([ 0,  1, 99,  3,  4,  5,  6,  7,  8,  9]),
 array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]))

In [136]:
original = np.arange(10)

single_value = original[5]  # single element access returns a copy
single_value

5

In [137]:
single_value = 9999
original             # not affected when `single_value` is changed

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

## Slices

In [138]:
original = np.arange(10)

a_slice = original[2:4]    # slice of original
a_slice

array([2, 3])

In [140]:
a_slice[1] = 1000  # changing elements of `a_slice` changes to `original`
original

array([   0,    1,    2, 1000,    4,    5,    6,    7,    8,    9])

In [142]:
original[3:6] = [101, 102, 103]   # changing 'original' also changes 'slice'
a_slice

array([  2, 101])

## Speed Comparisons

In [5]:
def my_mean(numbers):
    s = 0
    N = len(numbers)
    for i in range(N):
        s += numbers[i]
    return s/N

numbers = np.arange(1000000)
%timeit my_mean(numbers)

72.4 ms ± 196 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [2]:
def my_mean(numbers):
    return sum(numbers)/len(numbers)

numbers = list(range(1000000))
%timeit my_mean(numbers) # Defined function

4.76 ms ± 57.3 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)


In [3]:
numbers = np.arange(1000000)
%timeit np.mean(numbers) # Numpy function

317 µs ± 4.97 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)


In [6]:
import numba as nb

@nb.jit
def my_mean(numbers):
    s = 0
    N = len(numbers)
    for i in range(N):
        s += numbers[i]
    return s/N

numbers = np.arange(1000000)
%timeit my_mean(numbers)

159 µs ± 2.49 µs per loop (mean ± std. dev. of 7 runs, 1 loop each)


## Speed Comparisons

In [9]:
def my_sum(N):
    s = 0
    for i in range(N):
        s +=i
    return s

%timeit my_sum(100000000)

2.99 s ± 20.2 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)


In [10]:
numbers_to_sum = np.arange(100000000)
%timeit np.sum(numbers_to_sum)

38.3 ms ± 512 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [11]:
@nb.jit
def my_sum(N):
    s = 0
    for i in range(N):
        s +=i
    return s

%timeit my_sum(100000000)

70.2 ns ± 0.242 ns per loop (mean ± std. dev. of 7 runs, 10000000 loops each)


Use of built-in function is encouraged !!!